

spring.datasource.url=jdbc:mysql://localhost:3306/inventra_db
spring.datasource.username=root
spring.datasource.password=Vineeta@#tiwari

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8083